---
title: "Developing Data Products - Leaflet Examples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## `r Sys.Date()`


## Making Custom Markers

```{r, echo=TRUE}
library(leaflet)

hopkinsIcon <- makeIcon(
    iconUrl = "http://brand.jhu.edu/content/uploads/2014/06/university.shield.small_.blue_.png",
    iconWidth = 31*215/230, iconHeight = 31,
    iconAnchorX = 31*215/230/2, iconAnchorY = 16
)

hopkinsLatLong <- data.frame(
    lat = c(39.2973166, 39.3288851, 39.2906617, 39.2970681, 39.2824806),
    lng = c(-76.5929798, -76.6206598, -76.5469683, -76.6150537, -76.6016766)
)

hopkinsLatLong %>% leaflet() %>% addTiles() %>% addMarkers(icon=hopkinsIcon)

```


## Adding Multiple Popups
Add popups for each marker: you can specify a string of plain text for each popup, or you can provide HTML which will be rendered inside of each popup.

```{r, echo=TRUE}
hopkinsSites <- c(
    "<a href='http//www.jhsph.edu/'>East Baltimore Campus</a>",
    "<a href='http//apply.jhu.edu/visit/homewood/'>Homewood Campus</a>",
    "<a href='http//www.hopkinsmedicine.org/johns_hopkins_bayview/'>Bayview Medical Center</a>",
    "<a href='http//www.peabody.jhu.edu/'>Peabody Institute</a>",
    "<a href='http//carey.jhu.edu/'>Carey Business School</a>"
)

hopkinsLatLong %>% leaflet() %>% addTiles() %>% 
    addMarkers(icon=hopkinsIcon, popup=hopkinsSites)

```


## Mapping Clusters

```{r, echo=TRUE}
df <- data.frame(
    lat=runif(500, min=39.25, max=39.35),
    lng=runif(500, min=-76.65, max=-76.55)
)

df %>% leaflet() %>% addTiles() %>% 
    addMarkers(clusterOptions=markerClusterOptions())

```


## Mapping Circle Clusters

```{r, echo=TRUE}
df <- data.frame(
    lat=runif(20, min=39.25, max=39.35),
    lng=runif(20, min=-76.65, max=-76.55)
)

df %>% leaflet() %>% addTiles() %>% 
    addCircleMarkers()
```


## Mapping Circle Clusters

```{r, echo=TRUE}
df <- data.frame(
    lat=runif(20, min=39.25, max=39.35),
    lng=runif(20, min=-76.65, max=-76.55)
)

df %>% leaflet() %>% addTiles() %>% 
    addCircleMarkers()
```


## Drawing Shapes

```{r, echo=TRUE, warning=FALSE}
# - Draw a map where the circle on each city is proportional to the population of tha city

md_cities <- data.frame(
    name=c("Baltimore","Frederick","Rockville"),
    pop=c(619493, 66169, 62334),
    lat=c(39.2920592, 39.4143921, 39.0840),
    lng=c(-76.6077852, -77.4204875, -77.1528)
)

md_cities %>% leaflet() %>% addTiles() %>% 
    addCircles(weight=4, radius=sqrt(md_cities$pop)*30)

# -- Add Rectangles
leaflet() %>% addTiles() %>% 
    addRectangles(lat1=37.3858, lng1=-122.0595,
                  lat2=37.3890, lng2=-122.0625)

```


## Adding a legend

```{r, echo=TRUE, warning=FALSE}
df <- data.frame(
    lat=runif(20, min=39.25, max=39.35),
    lng=runif(20, min=-76.65, max=-76.55),
    col=sample(c("red","blue","green"), 20, replace=TRUE),
    stringsAsFactors = FALSE
)

df %>% leaflet() %>% addTiles() %>% 
    addCircleMarkers(color=df$col) %>%
    addLegend(labels=LETTERS[1:3], colors=c("blue","red","green"))

```







